[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
hook_add = '''
source ~/.config/nvim/plugins/vimfiler.rc.vim
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
source ~/.config/nvim/plugins/defx.rc.vim
'''

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/.config/nvim/plugins/denite.rc.vim
'''

[[plugins]]
repo = 'kmnk/denite-dirmark'

[[plugins]]
repo = 'N0nki/denite-markdown'

[[plugins]]
repo = 'chemzqm/unite-location'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
source ~/.config/nvim/plugins/airline.rc.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
source ~/.config/nvim/plugins/vim-gitgutter.rc.vim
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
source ~/.config/nvim/plugins/quickrun.rc.vim
'''

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'flazz/vim-colorschemes'
hook_add = '''
source ~/.config/nvim/plugins/colorschemes.rc.vim
'''

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
source ~/.config/nvim/plugins/vim-devicons.rc.vim
'''

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'mattn/gist-vim'
depends = ['mattn/webapi-vim']
hook_add = '''
source ~/.config/nvim/plugins/gist-vim.rc.vim
'''

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
source ~/.config/nvim/plugins/ale.rc.vim
'''

[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
source ~/.config/nvim/plugins/neoterm.rc.vim
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
source ~/.config/nvim/plugins/indentline.rc.vim
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['junegunn/fzf']
hook_add = '''
source ~/.config/nvim/plugins/fzf-vim.rc.vim
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
if = "!has('nvim')"
repo = 'haya14busa/is.vim'

[[plugins]]
if = "!has('nvim')"
repo = 'roxma/nvim-yarp'

[[plugins]]
if = "!has('nvim')"
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'wesQ3/vim-windowswap'
hook_add = '''
source ~/.config/nvim/plugins/vim-windowswap.rc.vim
'''
